require('dotenv').config({ path: require('path').join(__dirname, '../.env') });
const mongoose = require('mongoose');
const Topic = require('../modules/topics/topic.model');
const Problem = require('../modules/problems/problem.model');

const topics = [
  { title: 'Arrays', description: 'Fundamental array operations, sliding window, two pointers', order: 1 },
  { title: 'Strings', description: 'String manipulation, pattern matching, hashing', order: 2 },
  { title: 'Linked List', description: 'Singly, doubly linked lists, fast & slow pointers', order: 3 },
  { title: 'Stack & Queue', description: 'Monotonic stack, deque, circular queue', order: 4 },
  { title: 'Binary Search', description: 'Search on sorted arrays and answer spaces', order: 5 },
  { title: 'Sorting', description: 'Comparison and non-comparison based sorting algorithms', order: 6 },
  { title: 'Trees', description: 'Binary trees, BST, traversals, construction', order: 7 },
  { title: 'Graphs', description: 'BFS, DFS, shortest path, topological sort', order: 8 },
  { title: 'Dynamic Programming', description: 'Memoization, tabulation, classic DP patterns', order: 9 },
  { title: 'Recursion & Backtracking', description: 'Subsets, permutations, constraint satisfaction', order: 10 },
];

const problemsData = [
  // ─── Arrays ──────────────────────────────────────────────────────────────────
  { topicKey: 'Arrays', title: 'Two Sum', difficulty: 'Easy', order: 1,
    practiceLink: 'https://leetcode.com/problems/two-sum/',
    youtubeLink: 'https://www.youtube.com/watch?v=KLlXCFG5TnA',
    articleLink: 'https://www.geeksforgeeks.org/two-sum-problem/' },
  { topicKey: 'Arrays', title: 'Best Time to Buy and Sell Stock', difficulty: 'Easy', order: 2,
    practiceLink: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/',
    youtubeLink: 'https://www.youtube.com/watch?v=1pkOgXD63yU',
    articleLink: 'https://www.geeksforgeeks.org/best-time-to-buy-and-sell-stock/' },
  { topicKey: 'Arrays', title: 'Contains Duplicate', difficulty: 'Easy', order: 3,
    practiceLink: 'https://leetcode.com/problems/contains-duplicate/',
    youtubeLink: 'https://www.youtube.com/watch?v=3OamzN90kPg',
    articleLink: 'https://www.geeksforgeeks.org/check-if-array-contains-duplicate/' },
  { topicKey: 'Arrays', title: 'Maximum Subarray (Kadane\'s Algorithm)', difficulty: 'Medium', order: 4,
    practiceLink: 'https://leetcode.com/problems/maximum-subarray/',
    youtubeLink: 'https://www.youtube.com/watch?v=5WZl3MMT0Eg',
    articleLink: 'https://www.geeksforgeeks.org/largest-sum-contiguous-subarray/' },
  { topicKey: 'Arrays', title: 'Product of Array Except Self', difficulty: 'Medium', order: 5,
    practiceLink: 'https://leetcode.com/problems/product-of-array-except-self/',
    youtubeLink: 'https://www.youtube.com/watch?v=bNvIQI2wAjk',
    articleLink: 'https://www.geeksforgeeks.org/product-array-puzzle/' },
  { topicKey: 'Arrays', title: 'Maximum Product Subarray', difficulty: 'Medium', order: 6,
    practiceLink: 'https://leetcode.com/problems/maximum-product-subarray/',
    youtubeLink: 'https://www.youtube.com/watch?v=lXVy6YWFcRM',
    articleLink: 'https://www.geeksforgeeks.org/maximum-product-subarray/' },
  { topicKey: 'Arrays', title: 'Find Minimum in Rotated Sorted Array', difficulty: 'Medium', order: 7,
    practiceLink: 'https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/',
    youtubeLink: 'https://www.youtube.com/watch?v=nIVW4P8b1VA',
    articleLink: 'https://www.geeksforgeeks.org/find-minimum-element-in-a-sorted-and-rotated-array/' },
  { topicKey: 'Arrays', title: '3Sum', difficulty: 'Medium', order: 8,
    practiceLink: 'https://leetcode.com/problems/3sum/',
    youtubeLink: 'https://www.youtube.com/watch?v=jzZsG8n2R9A',
    articleLink: 'https://www.geeksforgeeks.org/find-a-triplet-that-sum-to-a-given-value/' },
  { topicKey: 'Arrays', title: 'Container With Most Water', difficulty: 'Medium', order: 9,
    practiceLink: 'https://leetcode.com/problems/container-with-most-water/',
    youtubeLink: 'https://www.youtube.com/watch?v=UuiTKBwPgAo',
    articleLink: 'https://www.geeksforgeeks.org/container-with-most-water/' },
  { topicKey: 'Arrays', title: 'Trapping Rain Water', difficulty: 'Tough', order: 10,
    practiceLink: 'https://leetcode.com/problems/trapping-rain-water/',
    youtubeLink: 'https://www.youtube.com/watch?v=ZI2z5pq0TqA',
    articleLink: 'https://www.geeksforgeeks.org/trapping-rain-water/' },

  // ─── Strings ─────────────────────────────────────────────────────────────────
  { topicKey: 'Strings', title: 'Valid Anagram', difficulty: 'Easy', order: 1,
    practiceLink: 'https://leetcode.com/problems/valid-anagram/',
    youtubeLink: 'https://www.youtube.com/watch?v=9UtInBqnCgA',
    articleLink: 'https://www.geeksforgeeks.org/check-whether-two-strings-are-anagram-of-each-other/' },
  { topicKey: 'Strings', title: 'Valid Palindrome', difficulty: 'Easy', order: 2,
    practiceLink: 'https://leetcode.com/problems/valid-palindrome/',
    youtubeLink: 'https://www.youtube.com/watch?v=jJXJ16kPFWg',
    articleLink: 'https://www.geeksforgeeks.org/check-if-a-number-is-palindrome/' },
  { topicKey: 'Strings', title: 'Longest Substring Without Repeating Characters', difficulty: 'Medium', order: 3,
    practiceLink: 'https://leetcode.com/problems/longest-substring-without-repeating-characters/',
    youtubeLink: 'https://www.youtube.com/watch?v=wiGpQwVHdE0',
    articleLink: 'https://www.geeksforgeeks.org/length-of-the-longest-substring-without-repeating-characters/' },
  { topicKey: 'Strings', title: 'Longest Repeating Character Replacement', difficulty: 'Medium', order: 4,
    practiceLink: 'https://leetcode.com/problems/longest-repeating-character-replacement/',
    youtubeLink: 'https://www.youtube.com/watch?v=gqXU1UyA8pk',
    articleLink: 'https://www.geeksforgeeks.org/longest-repeating-character-replacement/' },
  { topicKey: 'Strings', title: 'Group Anagrams', difficulty: 'Medium', order: 5,
    practiceLink: 'https://leetcode.com/problems/group-anagrams/',
    youtubeLink: 'https://www.youtube.com/watch?v=vzdNOK2oB2E',
    articleLink: 'https://www.geeksforgeeks.org/given-a-sequence-of-words-print-all-anagrams-together/' },
  { topicKey: 'Strings', title: 'Minimum Window Substring', difficulty: 'Tough', order: 6,
    practiceLink: 'https://leetcode.com/problems/minimum-window-substring/',
    youtubeLink: 'https://www.youtube.com/watch?v=jSto0O4AJbM',
    articleLink: 'https://www.geeksforgeeks.org/find-the-smallest-window-in-a-string-containing-all-characters-of-another-string/' },
  { topicKey: 'Strings', title: 'Encode and Decode Strings', difficulty: 'Medium', order: 7,
    practiceLink: 'https://leetcode.com/problems/encode-and-decode-strings/',
    youtubeLink: 'https://www.youtube.com/watch?v=B1k_sxOSgv8',
    articleLink: 'https://www.geeksforgeeks.org/encode-and-decode-strings/' },
  { topicKey: 'Strings', title: 'Palindromic Substrings', difficulty: 'Medium', order: 8,
    practiceLink: 'https://leetcode.com/problems/palindromic-substrings/',
    youtubeLink: 'https://www.youtube.com/watch?v=4RACzI5-du8',
    articleLink: 'https://www.geeksforgeeks.org/count-palindrome-sub-strings-of-a-string/' },

  // ─── Linked List ─────────────────────────────────────────────────────────────
  { topicKey: 'Linked List', title: 'Reverse a Linked List', difficulty: 'Easy', order: 1,
    practiceLink: 'https://leetcode.com/problems/reverse-linked-list/',
    youtubeLink: 'https://www.youtube.com/watch?v=G0_I-ZF0S38',
    articleLink: 'https://www.geeksforgeeks.org/reverse-a-linked-list/' },
  { topicKey: 'Linked List', title: 'Detect Cycle in Linked List', difficulty: 'Easy', order: 2,
    practiceLink: 'https://leetcode.com/problems/linked-list-cycle/',
    youtubeLink: 'https://www.youtube.com/watch?v=wiOo4DC5GGA',
    articleLink: 'https://www.geeksforgeeks.org/detect-loop-in-a-linked-list/' },
  { topicKey: 'Linked List', title: 'Merge Two Sorted Lists', difficulty: 'Easy', order: 3,
    practiceLink: 'https://leetcode.com/problems/merge-two-sorted-lists/',
    youtubeLink: 'https://www.youtube.com/watch?v=XIdigk956u0',
    articleLink: 'https://www.geeksforgeeks.org/merge-two-sorted-linked-lists/' },
  { topicKey: 'Linked List', title: 'Remove Nth Node From End', difficulty: 'Medium', order: 4,
    practiceLink: 'https://leetcode.com/problems/remove-nth-node-from-end-of-list/',
    youtubeLink: 'https://www.youtube.com/watch?v=XVuQxVej6y8',
    articleLink: 'https://www.geeksforgeeks.org/delete-nth-node-from-the-end-of-the-given-linked-list/' },
  { topicKey: 'Linked List', title: 'Reorder Linked List', difficulty: 'Medium', order: 5,
    practiceLink: 'https://leetcode.com/problems/reorder-list/',
    youtubeLink: 'https://www.youtube.com/watch?v=S5bfdUTrKLM',
    articleLink: 'https://www.geeksforgeeks.org/rearrange-a-given-linked-list-in-place/' },
  { topicKey: 'Linked List', title: 'Merge K Sorted Lists', difficulty: 'Tough', order: 6,
    practiceLink: 'https://leetcode.com/problems/merge-k-sorted-lists/',
    youtubeLink: 'https://www.youtube.com/watch?v=q5a5OiGbT6Q',
    articleLink: 'https://www.geeksforgeeks.org/merge-k-sorted-linked-lists/' },
  { topicKey: 'Linked List', title: 'LRU Cache', difficulty: 'Tough', order: 7,
    practiceLink: 'https://leetcode.com/problems/lru-cache/',
    youtubeLink: 'https://www.youtube.com/watch?v=7ABFKPK2hD4',
    articleLink: 'https://www.geeksforgeeks.org/lru-cache-implementation/' },

  // ─── Stack & Queue ────────────────────────────────────────────────────────────
  { topicKey: 'Stack & Queue', title: 'Valid Parentheses', difficulty: 'Easy', order: 1,
    practiceLink: 'https://leetcode.com/problems/valid-parentheses/',
    youtubeLink: 'https://www.youtube.com/watch?v=WTzjTskDFMg',
    articleLink: 'https://www.geeksforgeeks.org/check-for-balanced-parentheses-in-an-expression/' },
  { topicKey: 'Stack & Queue', title: 'Min Stack', difficulty: 'Medium', order: 2,
    practiceLink: 'https://leetcode.com/problems/min-stack/',
    youtubeLink: 'https://www.youtube.com/watch?v=WxTWL-RQ4Cs',
    articleLink: 'https://www.geeksforgeeks.org/design-a-stack-that-supports-getmin-in-o1-time-and-o1-extra-space/' },
  { topicKey: 'Stack & Queue', title: 'Daily Temperatures', difficulty: 'Medium', order: 3,
    practiceLink: 'https://leetcode.com/problems/daily-temperatures/',
    youtubeLink: 'https://www.youtube.com/watch?v=cTBiBSnjO3c',
    articleLink: 'https://www.geeksforgeeks.org/next-greater-element/' },
  { topicKey: 'Stack & Queue', title: 'Implement Queue using Stacks', difficulty: 'Easy', order: 4,
    practiceLink: 'https://leetcode.com/problems/implement-queue-using-stacks/',
    youtubeLink: 'https://www.youtube.com/watch?v=eanwa3ht3YQ',
    articleLink: 'https://www.geeksforgeeks.org/queue-using-stacks/' },
  { topicKey: 'Stack & Queue', title: 'Largest Rectangle in Histogram', difficulty: 'Tough', order: 5,
    practiceLink: 'https://leetcode.com/problems/largest-rectangle-in-histogram/',
    youtubeLink: 'https://www.youtube.com/watch?v=zx5Sw9130L0',
    articleLink: 'https://www.geeksforgeeks.org/largest-rectangle-under-histogram/' },
  { topicKey: 'Stack & Queue', title: 'Sliding Window Maximum', difficulty: 'Tough', order: 6,
    practiceLink: 'https://leetcode.com/problems/sliding-window-maximum/',
    youtubeLink: 'https://www.youtube.com/watch?v=DfljaUwZsOk',
    articleLink: 'https://www.geeksforgeeks.org/sliding-window-maximum-maximum-of-all-subarrays-of-size-k/' },

  // ─── Binary Search ────────────────────────────────────────────────────────────
  { topicKey: 'Binary Search', title: 'Binary Search', difficulty: 'Easy', order: 1,
    practiceLink: 'https://leetcode.com/problems/binary-search/',
    youtubeLink: 'https://www.youtube.com/watch?v=s4DPM8ct1pI',
    articleLink: 'https://www.geeksforgeeks.org/binary-search/' },
  { topicKey: 'Binary Search', title: 'Search in Rotated Sorted Array', difficulty: 'Medium', order: 2,
    practiceLink: 'https://leetcode.com/problems/search-in-rotated-sorted-array/',
    youtubeLink: 'https://www.youtube.com/watch?v=U8XENwh8Oy8',
    articleLink: 'https://www.geeksforgeeks.org/search-an-element-in-a-sorted-and-pivoted-array/' },
  { topicKey: 'Binary Search', title: 'Find Peak Element', difficulty: 'Medium', order: 3,
    practiceLink: 'https://leetcode.com/problems/find-peak-element/',
    youtubeLink: 'https://www.youtube.com/watch?v=HtSuA80QTyo',
    articleLink: 'https://www.geeksforgeeks.org/find-a-peak-in-a-given-array/' },
  { topicKey: 'Binary Search', title: 'Koko Eating Bananas', difficulty: 'Medium', order: 4,
    practiceLink: 'https://leetcode.com/problems/koko-eating-bananas/',
    youtubeLink: 'https://www.youtube.com/watch?v=U2SozAs9RzA',
    articleLink: 'https://www.geeksforgeeks.org/koko-eating-bananas/' },
  { topicKey: 'Binary Search', title: 'Median of Two Sorted Arrays', difficulty: 'Tough', order: 5,
    practiceLink: 'https://leetcode.com/problems/median-of-two-sorted-arrays/',
    youtubeLink: 'https://www.youtube.com/watch?v=q6IEA26hvXc',
    articleLink: 'https://www.geeksforgeeks.org/median-of-two-sorted-arrays/' },

  // ─── Sorting ──────────────────────────────────────────────────────────────────
  { topicKey: 'Sorting', title: 'Sort Colors (Dutch National Flag)', difficulty: 'Medium', order: 1,
    practiceLink: 'https://leetcode.com/problems/sort-colors/',
    youtubeLink: 'https://www.youtube.com/watch?v=tp8JIuCXBaU',
    articleLink: 'https://www.geeksforgeeks.org/sort-an-array-of-0s-1s-and-2s/' },
  { topicKey: 'Sorting', title: 'Merge Sort', difficulty: 'Medium', order: 2,
    practiceLink: 'https://leetcode.com/problems/sort-an-array/',
    youtubeLink: 'https://www.youtube.com/watch?v=TzeBrDU-JaY',
    articleLink: 'https://www.geeksforgeeks.org/merge-sort/' },
  { topicKey: 'Sorting', title: 'Quick Sort', difficulty: 'Medium', order: 3,
    practiceLink: 'https://leetcode.com/problems/sort-an-array/',
    youtubeLink: 'https://www.youtube.com/watch?v=7h1s2SojIRw',
    articleLink: 'https://www.geeksforgeeks.org/quick-sort/' },
  { topicKey: 'Sorting', title: 'Kth Largest Element in Array', difficulty: 'Medium', order: 4,
    practiceLink: 'https://leetcode.com/problems/kth-largest-element-in-an-array/',
    youtubeLink: 'https://www.youtube.com/watch?v=XEmy13g1Qxc',
    articleLink: 'https://www.geeksforgeeks.org/kth-smallestlargest-element-in-unsorted-array/' },
  { topicKey: 'Sorting', title: 'Count Inversions in Array', difficulty: 'Tough', order: 5,
    practiceLink: 'https://www.geeksforgeeks.org/problems/inversion-of-array-1587115620/1',
    youtubeLink: 'https://www.youtube.com/watch?v=kQ1mJlwW-c0',
    articleLink: 'https://www.geeksforgeeks.org/counting-inversions/' },

  // ─── Trees ────────────────────────────────────────────────────────────────────
  { topicKey: 'Trees', title: 'Inorder Traversal', difficulty: 'Easy', order: 1,
    practiceLink: 'https://leetcode.com/problems/binary-tree-inorder-traversal/',
    youtubeLink: 'https://www.youtube.com/watch?v=Z_NEgBgbRVI',
    articleLink: 'https://www.geeksforgeeks.org/inorder-traversal-of-binary-tree/' },
  { topicKey: 'Trees', title: 'Level Order Traversal (BFS)', difficulty: 'Medium', order: 2,
    practiceLink: 'https://leetcode.com/problems/binary-tree-level-order-traversal/',
    youtubeLink: 'https://www.youtube.com/watch?v=6ZnyEApgFYg',
    articleLink: 'https://www.geeksforgeeks.org/level-order-tree-traversal/' },
  { topicKey: 'Trees', title: 'Maximum Depth of Binary Tree', difficulty: 'Easy', order: 3,
    practiceLink: 'https://leetcode.com/problems/maximum-depth-of-binary-tree/',
    youtubeLink: 'https://www.youtube.com/watch?v=hTM3phVI6YQ',
    articleLink: 'https://www.geeksforgeeks.org/find-the-maximum-depth-or-height-of-a-tree/' },
  { topicKey: 'Trees', title: 'Lowest Common Ancestor of BST', difficulty: 'Medium', order: 4,
    practiceLink: 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/',
    youtubeLink: 'https://www.youtube.com/watch?v=gs2LMfuOR9k',
    articleLink: 'https://www.geeksforgeeks.org/lowest-common-ancestor-in-a-binary-search-tree/' },
  { topicKey: 'Trees', title: 'Validate Binary Search Tree', difficulty: 'Medium', order: 5,
    practiceLink: 'https://leetcode.com/problems/validate-binary-search-tree/',
    youtubeLink: 'https://www.youtube.com/watch?v=s6ATEkipzow',
    articleLink: 'https://www.geeksforgeeks.org/a-program-to-check-if-a-binary-tree-is-bst-or-not/' },
  { topicKey: 'Trees', title: 'Diameter of Binary Tree', difficulty: 'Easy', order: 6,
    practiceLink: 'https://leetcode.com/problems/diameter-of-binary-tree/',
    youtubeLink: 'https://www.youtube.com/watch?v=bkxqA8Rfv04',
    articleLink: 'https://www.geeksforgeeks.org/diameter-of-a-binary-tree/' },
  { topicKey: 'Trees', title: 'Binary Tree Maximum Path Sum', difficulty: 'Tough', order: 7,
    practiceLink: 'https://leetcode.com/problems/binary-tree-maximum-path-sum/',
    youtubeLink: 'https://www.youtube.com/watch?v=Hr5cWUld4vU',
    articleLink: 'https://www.geeksforgeeks.org/find-maximum-path-sum-in-a-binary-tree/' },
  { topicKey: 'Trees', title: 'Serialize and Deserialize Binary Tree', difficulty: 'Tough', order: 8,
    practiceLink: 'https://leetcode.com/problems/serialize-and-deserialize-binary-tree/',
    youtubeLink: 'https://www.youtube.com/watch?v=-YbXySKJsX8',
    articleLink: 'https://www.geeksforgeeks.org/serialize-deserialize-binary-tree/' },

  // ─── Graphs ───────────────────────────────────────────────────────────────────
  { topicKey: 'Graphs', title: 'Number of Islands', difficulty: 'Medium', order: 1,
    practiceLink: 'https://leetcode.com/problems/number-of-islands/',
    youtubeLink: 'https://www.youtube.com/watch?v=pV2kpPD66nE',
    articleLink: 'https://www.geeksforgeeks.org/find-the-number-of-islands-using-dfs/' },
  { topicKey: 'Graphs', title: 'Clone Graph', difficulty: 'Medium', order: 2,
    practiceLink: 'https://leetcode.com/problems/clone-graph/',
    youtubeLink: 'https://www.youtube.com/watch?v=mQeF6bN8hMk',
    articleLink: 'https://www.geeksforgeeks.org/clone-an-undirected-graph/' },
  { topicKey: 'Graphs', title: 'Course Schedule (Topological Sort)', difficulty: 'Medium', order: 3,
    practiceLink: 'https://leetcode.com/problems/course-schedule/',
    youtubeLink: 'https://www.youtube.com/watch?v=EgI5nU9etnU',
    articleLink: 'https://www.geeksforgeeks.org/detect-cycle-in-a-graph/' },
  { topicKey: 'Graphs', title: 'Pacific Atlantic Water Flow', difficulty: 'Medium', order: 4,
    practiceLink: 'https://leetcode.com/problems/pacific-atlantic-water-flow/',
    youtubeLink: 'https://www.youtube.com/watch?v=s-VIfNTdB10',
    articleLink: 'https://www.geeksforgeeks.org/pacific-atlantic-water-flow/' },
  { topicKey: 'Graphs', title: 'Dijkstra\'s Shortest Path', difficulty: 'Medium', order: 5,
    practiceLink: 'https://www.geeksforgeeks.org/problems/implementing-dijkstra-set-1-adjacency-matrix/1',
    youtubeLink: 'https://www.youtube.com/watch?v=V6H1qAeB-l4',
    articleLink: 'https://www.geeksforgeeks.org/dijkstras-shortest-path-algorithm-greedy-algo-7/' },
  { topicKey: 'Graphs', title: 'Word Ladder', difficulty: 'Tough', order: 6,
    practiceLink: 'https://leetcode.com/problems/word-ladder/',
    youtubeLink: 'https://www.youtube.com/watch?v=h9iTnkgv05E',
    articleLink: 'https://www.geeksforgeeks.org/word-ladder-length-of-shortest-chain-to-reach-a-target-word/' },
  { topicKey: 'Graphs', title: 'Alien Dictionary', difficulty: 'Tough', order: 7,
    practiceLink: 'https://www.geeksforgeeks.org/problems/alien-dictionary/1',
    youtubeLink: 'https://www.youtube.com/watch?v=6kTZYvNNyps',
    articleLink: 'https://www.geeksforgeeks.org/given-sorted-dictionary-find-precedence-characters/' },

  // ─── Dynamic Programming ──────────────────────────────────────────────────────
  { topicKey: 'Dynamic Programming', title: 'Climbing Stairs', difficulty: 'Easy', order: 1,
    practiceLink: 'https://leetcode.com/problems/climbing-stairs/',
    youtubeLink: 'https://www.youtube.com/watch?v=Y0lT9Fck7qI',
    articleLink: 'https://www.geeksforgeeks.org/count-ways-reach-nth-stair/' },
  { topicKey: 'Dynamic Programming', title: 'House Robber', difficulty: 'Medium', order: 2,
    practiceLink: 'https://leetcode.com/problems/house-robber/',
    youtubeLink: 'https://www.youtube.com/watch?v=73r3KWiEvyk',
    articleLink: 'https://www.geeksforgeeks.org/find-maximum-possible-stolen-value-houses/' },
  { topicKey: 'Dynamic Programming', title: '0/1 Knapsack Problem', difficulty: 'Medium', order: 3,
    practiceLink: 'https://www.geeksforgeeks.org/problems/0-1-knapsack-problem0945/1',
    youtubeLink: 'https://www.youtube.com/watch?v=8LusJS5-AGo',
    articleLink: 'https://www.geeksforgeeks.org/0-1-knapsack-problem-dp-10/' },
  { topicKey: 'Dynamic Programming', title: 'Longest Common Subsequence', difficulty: 'Medium', order: 4,
    practiceLink: 'https://leetcode.com/problems/longest-common-subsequence/',
    youtubeLink: 'https://www.youtube.com/watch?v=Ua0GhIs5wWA',
    articleLink: 'https://www.geeksforgeeks.org/longest-common-subsequence-dp-4/' },
  { topicKey: 'Dynamic Programming', title: 'Coin Change', difficulty: 'Medium', order: 5,
    practiceLink: 'https://leetcode.com/problems/coin-change/',
    youtubeLink: 'https://www.youtube.com/watch?v=H9bfqozjoqs',
    articleLink: 'https://www.geeksforgeeks.org/coin-change-dp-7/' },
  { topicKey: 'Dynamic Programming', title: 'Longest Increasing Subsequence', difficulty: 'Medium', order: 6,
    practiceLink: 'https://leetcode.com/problems/longest-increasing-subsequence/',
    youtubeLink: 'https://www.youtube.com/watch?v=cjWnW0hdF1Y',
    articleLink: 'https://www.geeksforgeeks.org/longest-increasing-subsequence-dp-3/' },
  { topicKey: 'Dynamic Programming', title: 'Word Break', difficulty: 'Medium', order: 7,
    practiceLink: 'https://leetcode.com/problems/word-break/',
    youtubeLink: 'https://www.youtube.com/watch?v=Sx9NNgInc3A',
    articleLink: 'https://www.geeksforgeeks.org/word-break-problem-dp-32/' },
  { topicKey: 'Dynamic Programming', title: 'Unique Paths', difficulty: 'Medium', order: 8,
    practiceLink: 'https://leetcode.com/problems/unique-paths/',
    youtubeLink: 'https://www.youtube.com/watch?v=IlEsdxuD4lY',
    articleLink: 'https://www.geeksforgeeks.org/count-possible-paths-top-left-bottom-right-nxm-matrix/' },
  { topicKey: 'Dynamic Programming', title: 'Edit Distance', difficulty: 'Tough', order: 9,
    practiceLink: 'https://leetcode.com/problems/edit-distance/',
    youtubeLink: 'https://www.youtube.com/watch?v=We3YDTzNXEk',
    articleLink: 'https://www.geeksforgeeks.org/edit-distance-dp-5/' },
  { topicKey: 'Dynamic Programming', title: 'Burst Balloons', difficulty: 'Tough', order: 10,
    practiceLink: 'https://leetcode.com/problems/burst-balloons/',
    youtubeLink: 'https://www.youtube.com/watch?v=VFskby7lUbw',
    articleLink: 'https://www.geeksforgeeks.org/burst-balloon-to-maximize-coins/' },

  // ─── Recursion & Backtracking ─────────────────────────────────────────────────
  { topicKey: 'Recursion & Backtracking', title: 'Subsets', difficulty: 'Medium', order: 1,
    practiceLink: 'https://leetcode.com/problems/subsets/',
    youtubeLink: 'https://www.youtube.com/watch?v=REOH22Xwdkk',
    articleLink: 'https://www.geeksforgeeks.org/power-set/' },
  { topicKey: 'Recursion & Backtracking', title: 'Permutations', difficulty: 'Medium', order: 2,
    practiceLink: 'https://leetcode.com/problems/permutations/',
    youtubeLink: 'https://www.youtube.com/watch?v=s7AvT7cGdSo',
    articleLink: 'https://www.geeksforgeeks.org/write-a-c-program-to-print-all-permutations-of-a-given-string/' },
  { topicKey: 'Recursion & Backtracking', title: 'Combination Sum', difficulty: 'Medium', order: 3,
    practiceLink: 'https://leetcode.com/problems/combination-sum/',
    youtubeLink: 'https://www.youtube.com/watch?v=GBKI9VSKdGg',
    articleLink: 'https://www.geeksforgeeks.org/combinational-sum/' },
  { topicKey: 'Recursion & Backtracking', title: 'Word Search', difficulty: 'Medium', order: 4,
    practiceLink: 'https://leetcode.com/problems/word-search/',
    youtubeLink: 'https://www.youtube.com/watch?v=pfiQ_PS1g8E',
    articleLink: 'https://www.geeksforgeeks.org/search-a-word-in-a-2d-grid-of-characters/' },
  { topicKey: 'Recursion & Backtracking', title: 'N-Queens', difficulty: 'Tough', order: 5,
    practiceLink: 'https://leetcode.com/problems/n-queens/',
    youtubeLink: 'https://www.youtube.com/watch?v=i05Ju7AR6cs',
    articleLink: 'https://www.geeksforgeeks.org/n-queen-problem-backtracking-3/' },
];

async function seed() {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log('Connected to MongoDB');

    await Topic.deleteMany({});
    await Problem.deleteMany({});
    console.log('Cleared existing data');

    const createdTopics = await Topic.insertMany(topics);
    const topicMap = {};
    createdTopics.forEach((t) => { topicMap[t.title] = t._id; });
    console.log(`Seeded ${createdTopics.length} topics`);

    const problems = problemsData.map(({ topicKey, ...rest }) => ({
      ...rest,
      topicId: topicMap[topicKey],
    }));

    await Problem.insertMany(problems);
    console.log(`Seeded ${problems.length} problems`);

    console.log('Seed complete!');
    process.exit(0);
  } catch (err) {
    console.error('Seed failed:', err);
    process.exit(1);
  }
}

seed();
